# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 72f4094bb78719266849344618019a4730f2a821ff966b60644515db88fb1a164e491c17b916cd522e7d2aa34f147d681b6e8fecef5c10c6b6ac3a7b88c387dc

test:
  secret_key_base: 3e78cc0d240c76a859dae2e5f34c6cebaaaca51dd97bdbe5004d644e678fffeb4549b0c1352bcebdfe4f43e036615b9d09a1ca4687129d7b34abd3d312654079

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
