# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: c92433124bb0280255940413cbea717dcd441e3b15ae92a78a5aa501df62e050e084ca5d8d72c7b00e1ee46b18a2bc1a370b6a6c8e46c82d33e77f1aa3392575

test:
  secret_key_base: 898607c71fa2664745b8e6e475512b64061a2fb409429055c100d48f28e39aa5796e59195b348e681ffda92739f3107e1a7c7a5fe6816db74a6a6ac17563fea0

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
